In [1]:
import pandas as pd
import numpy as np

In [3]:
# load 'iris' dataset
Iris = pd.read_csv('Iris 3 Groups.csv')

In [4]:
Iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   sapallength  150 non-null    float64
 1   sepalwidth   150 non-null    float64
 2   petallength  150 non-null    float64
 3   petalwith    150 non-null    float64
 4   Class        150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [5]:
Iris

sapallength  sepalwidth  petallength  petalwith           Class
0            5.1         3.5          1.4        0.2     Iris-setosa
1            4.9         3.0          1.4        0.2     Iris-setosa
2            4.7         3.2          1.3        0.2     Iris-setosa
3            4.6         3.1          1.5        0.2     Iris-setosa
4            5.0         3.6          1.4        0.2     Iris-setosa
..           ...         ...          ...        ...             ...
145          6.7         3.0          5.2        2.3  Iris-virginica
146          6.3         2.5          5.0        1.9  Iris-virginica
147          6.5         3.0          5.2        2.0  Iris-virginica
148          6.2         3.4          5.4        2.3  Iris-virginica
149          5.9         3.0          5.1        1.8  Iris-virginica

[150 rows x 5 columns]

In [6]:
features = ['sapallength','sepalwidth','petallength','petalwith']

In [7]:
# We will need to build the clustering model using features only, ‘Class’ is used for evaluation purpose later
X = Iris [features]
y = Iris ['Class']

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state = 42)

In [10]:
# import KMeans from sklearn
from sklearn.cluster import KMeans

In [11]:
# set number of cluster to be 3
kmeansmodel = KMeans(n_clusters=3)

In [12]:
# fit data
kmeansmodel.fit(X_train)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html
1. n_clusters:The number of clusters to form as well as the number of centroids to generate.
2. init: Method for initialization
3. n_init: Number of time the k-means algorithm will be run with different centroid seeds. The final results will be the best output of n_init consecutive runs in terms of inertia.
4. max_iter: Maximum number of iterations of the k-means algorithm for a single run.

In [13]:
# centroids
centroids = kmeansmodel.cluster_centers_
centroids

array([[4.94444444, 3.33333333, 1.46296296, 0.24074074],
       [6.75769231, 3.08846154, 5.60384615, 2.02307692],
       [5.7972973 , 2.69459459, 4.34864865, 1.42432432]])

In [14]:
# number of iteration 
interation = kmeansmodel.n_iter_
interation

4

In [15]:
#Sum of squared distances of samples to their closest cluster center
SSD = kmeansmodel.inertia_
SSD

46.44977323477323

In [16]:
# Transform X to a cluster-distance space
distance = kmeansmodel.transform(X_train)
distance

array([[4.0599452 , 0.95160251, 0.83538   ],
       [0.46687238, 4.579487  , 2.99784071],
       [0.36692845, 4.73832261, 3.12777795],
       [0.38563008, 4.51137123, 2.95338016],
       [3.07315247, 1.9961909 , 0.27660152],
       [0.17797057, 4.79689094, 3.25539391],
       [3.01554728, 1.94287882, 0.41851768],
       [6.25108934, 1.62082874, 3.31251032],
       [0.37688711, 5.06596574, 3.44709361],
       [3.30681219, 1.60293278, 0.47136406],
       [4.10742411, 1.35283507, 0.89609982],
       [1.03217112, 4.87988111, 3.54233398],
       [3.84609078, 1.1304225 , 0.69225075],
       [4.13693922, 1.15632426, 0.88928776],
       [3.06784509, 2.2321448 , 0.76636754],
       [3.33586118, 1.8284528 , 0.52891554],
       [4.61753977, 0.72547679, 1.59119886],
       [2.98914818, 2.30187408, 0.6173354 ],
       [0.7811479 , 4.51401335, 3.11053489],
       [2.24099172, 3.17262468, 1.43913272],
       [4.4716605 , 0.6215437 , 1.22254509],
       [0.09910436, 4.9122462 , 3.34599725],
       [0.

In [17]:
train_label=kmeansmodel.labels_

In [18]:
trainlabels=pd.DataFrame(train_label,y_train,columns=['cluster'])
trainlabels

cluster
Class                   
Iris-virginica         2
Iris-setosa            0
Iris-setosa            0
Iris-setosa            0
Iris-versicolor        2
...                  ...
Iris-versicolor        2
Iris-virginica         2
Iris-setosa            0
Iris-versicolor        2
Iris-virginica         1

[90 rows x 1 columns]

In [31]:
Iris_virginica = trainlabels.loc['Iris-virginica']
Iris_setosa = trainlabels.loc['Iris-setosa']
Iris_versicolor = trainlabels.loc['Iris-versicolor']

In [33]:
Iris_versicolor

cluster
Class                   
Iris-versicolor        2
Iris-versicolor        2
Iris-versicolor        2
Iris-versicolor        2
Iris-versicolor        2
Iris-versicolor        2
Iris-versicolor        2
Iris-versicolor        2
Iris-versicolor        1
Iris-versicolor        2
Iris-versicolor        2
Iris-versicolor        2
Iris-versicolor        2
Iris-versicolor        2
Iris-versicolor        2
Iris-versicolor        2
Iris-versicolor        1
Iris-versicolor        2
Iris-versicolor        2
Iris-versicolor        2
Iris-versicolor        2
Iris-versicolor        2
Iris-versicolor        2
Iris-versicolor        2
Iris-versicolor        2
Iris-versicolor        1
Iris-versicolor        2
Iris-versicolor        2
Iris-versicolor        2
Iris-versicolor        2
Iris-versicolor        2

In [20]:
Iris_virginica[Iris_virginica.columns[0]].value_counts()

1    23
2     9
Name: cluster, dtype: int64

In [21]:
Iris_setosa[Iris_setosa.columns[0]].value_counts()

0    27
Name: cluster, dtype: int64

In [22]:
Iris_versicolor[Iris_versicolor.columns[0]].value_counts()

2    28
1     3
Name: cluster, dtype: int64

In [23]:
# predict cluster
testlabels = kmeansmodel.predict(X_test)
testlabels

array([2, 0, 1, 2, 1, 0, 2, 1, 2, 2, 1, 0, 0, 0, 0, 2, 1, 2, 2, 1, 0, 2,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 2, 0, 0, 1, 2, 0, 0, 0, 2, 2, 1, 0,
       0, 2, 1, 1, 2, 1, 2, 1, 2, 0, 1, 2, 0, 0, 0, 2], dtype=int32)

In [24]:
testdata=pd.DataFrame(testlabels,y_test,columns=['cluster assignment'])
testdata

cluster assignment
Class                              
Iris-versicolor                   2
Iris-setosa                       0
Iris-virginica                    1
Iris-versicolor                   2
Iris-versicolor                   1
Iris-setosa                       0
Iris-versicolor                   2
Iris-virginica                    1
Iris-versicolor                   2
Iris-versicolor                   2
Iris-virginica                    1
Iris-setosa                       0
Iris-setosa                       0
Iris-setosa                       0
Iris-setosa                       0
Iris-versicolor                   2
Iris-virginica                    1
Iris-versicolor                   2
Iris-versicolor                   2
Iris-virginica                    1
Iris-setosa                       0
Iris-virginica                    2
Iris-setosa                       0
Iris-virginica                    1
Iris-virginica                    1
Iris-virginica                    1
Iris-virginica                    1
Iris-virginica                    1
Iris-setosa                       0
Iris-setosa                       0
Iris-setosa                       0
Iris-setosa                       0
Iris-versicolor                   2
Iris-setosa                       0
Iris-setosa                       0
Iris-virginica                    1
Iris-versicolor                   2
Iris-setosa                       0
Iris-setosa                       0
Iris-setosa                       0
Iris-virginica                    2
Iris-versicolor                   2
Iris-versicolor                   1
Iris-setosa                       0
Iris-setosa                       0
Iris-versicolor                   2
Iris-virginica                    1
Iris-virginica                    1
Iris-versicolor                   2
Iris-virginica                    1
Iris-versicolor                   2
Iris-virginica                    1
Iris-versicolor                   2
Iris-setosa                       0
Iris-virginica                    1
Iris-versicolor                   2
Iris-setosa                       0
Iris-setosa                       0
Iris-setosa                       0
Iris-versicolor                   2

In [25]:
Iris_virginica_test = testdata.loc['Iris-virginica']
Iris_setosa_test = testdata.loc['Iris-setosa']
Iris_versicolor_test = testdata.loc['Iris-versicolor']

In [26]:
Iris_virginica_test[Iris_virginica_test.columns[0]].value_counts()

1    16
2     2
Name: cluster assignment, dtype: int64

In [27]:
Iris_setosa_test[Iris_setosa_test.columns[0]].value_counts()

0    23
Name: cluster assignment, dtype: int64

In [28]:
Iris_versicolor_test[Iris_versicolor_test.columns[0]].value_counts()

2    17
1     2
Name: cluster assignment, dtype: int64